server:
  port: 8085
spring:
  application:
    name: moviehub

  datasource:
    url: jdbc:postgresql://localhost:5432/moviehub
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    fail-on-missing-locations: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 3600000
  refresh-expiration: 604800000

cloudinary:
  cloud_name: ${CLOUDINARY_NAME}
  api_key: ${CLOUDINARY_KEY}
  api_secret: ${CLOUDINARY_SECRET}

tmdb:
  api:
    key: ${TMDB_KEY}
  base:
    url: https://api.themoviedb.org/3
  image:
    url: https://image.tmdb.org/t/p/original