server:
  port: 8085
spring:
  application:
    name: moviehub

  datasource:
    url: jdbc:postgresql://localhost:5432/moviehub
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    fail-on-missing-locations: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  access-expiration: 3600000
  refresh-expiration: 604800000

cloudinary:
  cloud_name: dxobmvnzz
  api_key: 842934247774816
  api_secret: kyMLWk9AKz1MZEVul-vw6LN68c8

tmdb:
  api:
    key: dbe35e8e2d73c8f03d627e28a585dd72
  base:
    url: https://api.themoviedb.org/3
  image:
    url: https://image.tmdb.org/t/p/original